# Generated by Django 5.0.7 on 2024-08-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts_completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_number_and_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('phone_cell', models.CharField(max_length=20)),
                ('phone_home', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_mobile', models.CharField(max_length=20)),
                ('school_contact_person', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_street_number_and_name', models.CharField(max_length=100)),
                ('company_city', models.CharField(max_length=100)),
                ('company_state_or_province', models.CharField(max_length=100)),
                ('company_postal_code', models.CharField(max_length=20)),
                ('company_country', models.CharField(max_length=100)),
                ('intern_supervisor', models.CharField(blank=True, max_length=100)),
                ('supervisor_phone', models.CharField(blank=True, max_length=20)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('intern_title', models.CharField(choices=[('Intern', 'Intern'), ('Student', 'Student'), ('Learner', 'Learner'), ('Graduate', 'Graduate'), ('Transferee', 'Transferee')], max_length=100)),
                ('duties_description', models.TextField()),
                ('hours', models.CharField(blank=True, null=True)),
                ('intern_signature', models.TextField()),
                ('hr_signature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='api.contracts_completed')),
            ],
        ),
    ]
